const list = [
  {
    id: 1,
    title: "Harry Potter y la piedra filosofal",
    author: "por J.K. Rowling",
    price: 299,
    img: "https://m.media-amazon.com/images/I/81pM4orRvFL._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Percy Jackson El ladrón del rayo",
    author: "por Rick Riordan",
    price: 260,
    img: "https://m.media-amazon.com/images/I/91QVAkfs+-L._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Poesía completa",
    author: "por Alejandra Pizarnik",
    price: 499,
    img: "https://m.media-amazon.com/images/I/718n5bNK15L._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Ranger Reject 2",
    author: "por Negi Haruba",
    price: 149,
    img: "https://m.media-amazon.com/images/I/81fFuqYj+oL._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "WTF con el SAT",
    author: "por Paulina Casso",
    price: 299,
    img: "https://m.media-amazon.com/images/I/81ILIYRxOEL._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "1984",
    author: "por George Orwell",
    price: 135,
    img: "https://m.media-amazon.com/images/I/41vePvjajvL._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "La caida",
    author: "por Albert Camus",
    price: 239,
    img: "https://m.media-amazon.com/images/I/61Og7hO+YeL._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Jojo's Bizzarre Adventure parte 7 07 Steel Ball Run",
    author: "por Hirohiko Araki",
    price: 189,
    img: "https://m.media-amazon.com/images/I/71aXXYpyDyL._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Komi-san can't communicate",
    author: "por Tomohito Oda",
    price: 159,
    img: "https://m.media-amazon.com/images/I/81pskGQgusL._SL1500_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Boxset Demon Slayer",
    author: "por Koyoharu Gotouge",
    price: 2857,
    img: "https://m.media-amazon.com/images/I/51YgQgLaOML._SL1200_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Darth Vader N.2 Omnibus",
    author: "por Kiron Gillen y Jason Aaron",
    price: 2119,
    img: "https://m.media-amazon.com/images/I/61zxaXSYOJL._SL1200_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Chainsaw Man Boxset N.1",
    author: "por Tatsuki Fujimoto",
    price: 1469,
    img: "https://m.media-amazon.com/images/I/71-2KyQYqNL._SL1500_.jpg",
    amount: 1,
  },
];

export default list;
